content:
  - name: posts
    label: Posts
    path: content/posts
    type: collection
    subfolders: false
    view:
      fields: [ title, date, tags ]
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: summary
        label: Summary
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text