baseURL = 'https://blog.plk.tw/'

title = '技術浮浪貢'

locale = 'zh-tw'
defaultContentLanguage = 'zh-tw'
hasCJKLanguage = true

enableRobotsTXT = true

#################################

theme = "hugo-bearblog"

[params]
  description = "Ki-su̍t Phû-lōng-kòng, 記錄一些軟體技術小玩意兒"
  enablePostNavigator = true
  dateFormat = "2006-01-02"

#################################

[permalinks]
[permalinks.page]
posts = '/posts/:year/:month/:slug'

[markup]
[markup.highlight]
#style = 'catppuccin-latte'
style = 'monokailight'
tabWidth = 8
lineNos = true
lineNumbersInTable = false
codeFences = true

[taxonomies]
series = 'series'
tag = 'tags'
