baseURL = 'https://blog.plk.tw/'

title = '技術浮浪貢 Ki-su̍t Phû-lōng-kòng'

locale = 'zh-tw'
defaultContentLanguage = 'zh-tw'
hasCJKLanguage = true

#################################

theme = "hugo-bearblog"

[params]
dateFormat = "2006-01-02"

#################################

[permalinks]
[permalinks.page]
posts = '/posts/:year/:month/:slug'

[markup]
[markup.highlight]
#style = 'catppuccin-latte'
style = 'monokailight'
tabWidth = 8

[taxonomies]
series = 'series'
tag = 'tags'
